version: '3'

services:
  pickles-api:
    container_name: pickles-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ./:/app/
    networks:
      - pickles-api
    depends_on:
      - pickles-database

  pickles-database:
    container_name: pickles-database
    image: mariadb
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_TCP_PORT= ${DB_PORT}
    ports:
      - "56198:56198"
    networks:
      - pickles-api

networks:
  pickles-api:
    driver: bridge

volumes:
  pickles-mddata: